services:
  - type: web
    name: techstackr
    env: ruby
    plan: starter
    buildCommand: |
      bundle install
      bundle exec rails assets:precompile
      bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: techstackr-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true

databases:
  - name: techstackr-db
    plan: starter
    databaseName: techstackr_production
    user: techstackr_user
